info:
    serviceLinks:
        api-doc: "${route.name}/docs/index.html"
    dependencies:
        skatteetaten: "skatteetaten"
    auroraVersion: ${aurora.version:local-dev}
    imageBuildTime: ${image.build.time:}

aurora:
    #setting a db here will create a datasource from a database with that name.
    #in AOC config file
    db: REFERANSEAPP

spring:
    profiles:
        active: local

logging:
    level:
      ske.aurora: DEBUG
      org:
        springframework: WARN
        apache.catalina: WARN
        hibernate: WARN

---
spring:
  profiles: local
  application:
    name: referanseapp
  datasource:
    # id: 02150c29-6ab9-4917-bd56-1ba63d4f46d5"
    url: ${refapp.datasource.url:jdbc:oracle:thin:@uil0map-drivein-db02:1521/dbhotel}
    username: ${refapp.datasource.username:MFBDNLMIQTWTWNWEQOMLPAAPJDKSYV}
    password: ${refapp.datasource.password:qWieNxGpdFcjVOHPiaCTcmJqYdgYkk}


management:
    port: 8081


logging:
    pattern:
      console: "%d [%-9.9thread] %-5level %logger %X - %msg %n%rEx{full}"

